pub mod builder_pattern;
pub mod command_pattern;
pub mod dyn_object;
pub mod extension;
pub mod iterator_option;
pub mod new_type_pattern;
pub mod strategy_pattern;
pub mod take_replace_usage;
pub mod visitor_pattern;
